defaults:
  - model: le_admm_pre_post
  - metrics: lensless
  - datasets: digicam_eval
  - dataloader: digicam
  - transforms: lensless
  - _self_

inferencer:
  device_tensors: [ "lensless", "psf", "lensed" ]
  device: auto
  save_path: "digicam_test"
  seed: 42
  from_pretrained: "saved/model_best.pth"