_target_: src.logger.CometMLWriter
project_name: "bhw-lensless-computational-imaging-plotnikov244"
workspace: null
run_id: null
run_name: "admm_baseline"
mode: "online"
log_code: false
log_graph: false
auto_metric_logging: false
auto_param_logging: false
log_checkpoints: true
id_length: 32
loss_names: [ "loss", "mse_loss", "lpips_loss" ]